graphite:
    host: graphite.price
    port: 2003
    http_port: 80
    metric_prefix: price_monitor_internal
    default_get_metric_time: "-14d"

parsers:
    www.itaka.pl:
        number:
            price: "strong[data-js-value='offerPrice']"
        string:
            name: "span[class='productName-holder']"
            country: "span[class='destination-title destination-country-region'] @data-product-country"
            city: "span[class='destination-title destination-country-region'] @data-product-region"
    www.x-kom.pl:
        number:
            price: "span[class='pull-right price']"
        string:
            name: "div[class='product-info'] h1[itemprop='name']"
    packages.wakacyjnipiraci.pl:
        number:
            price: "span[class='trip-price']"
        string:
            name: "h1[class='trip-heading'] a"
            country: "header[class='header-of'] nav span"

parser_helpers:
    things_to_delete:
        - " "
        - "\u00A0"
        - "zl"
        - "zł"
        - "pln"
    join_parsers:
        www.itaka.pl: "BasicParser"
        www.x-kom.pl: "BasicParser"
