graphite:
    host: localhost
    port: 2003
    metric_prefix: price_monitor_internal
    default_get_metric_time: "-14d"

parsers:
    mock-service-url.mock:
        number:
            price: "div[class='mock-div another-class'] span"
        string:
            name: "p[class='offer-name']"

parser_helpers:
    things_to_delete:
        - " "
        - "\u00A0"
        - "zl"
        - "zł"
        - "pln"
    join_parsers:
        www.itaka.pl: "BasicParser"
        www.x-kom.pl: "BasicParser"
